version: "3"

services:
  rts_m2_rust:
    build: "."
    environment:
      DATABASE_URL: postgres://postgres:password@postgresql/postgres
      # TODO ignored at the moment
      LISTEN_URL: 0.0.0.0:8080
      # RUST_LOG: trace,actix_server=trace,actix_web=trace
    depends_on:
      postgresql:
        condition: service_healthy
    ports:
      - 8080:8080

  postgresql:
    image: "postgres:14"
    environment:
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "postgres" ]
      timeout: 45s
      interval: 10s
      retries: 10
