[package]
name = "rts-server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rts-core = { path = "../rts-core" }
futures = "0.3"
tokio = { version = "1.16.1", features = ["full"] } # @TODO remove
